"use client";
import { useState } from "react";
import { supabase } from "@/lib/supabase";
import type { User } from "@supabase/supabase-js";
export default function SessionCapture({user,projectId,sessions,onSaved}:{user:User;projectId:string;sessions:any[];onSaved:()=>void}){
 const empty={title:'',summary:'',decisions:'',evidence:'',open_questions:'',next_actions:'',chat_url:''};const [form,setForm]=useState(empty);const [open,setOpen]=useState(false);
 async function save(e:React.FormEvent){e.preventDefault();const {error}=await supabase.from('project_sessions').insert({user_id:user.id,project_id:projectId,...form});if(error)return alert(error.message);setForm(empty);setOpen(false);onSaved()}
 return <section className="panel"><div className="head"><div><p className="eyebrow">Conversation and work history</p><h2>Project sessions</h2></div><button onClick={()=>setOpen(!open)}>{open?'Cancel':'Save session'}</button></div>
 {open&&<form className="session-form" onSubmit={save}><label>Session title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><label>ChatGPT or source link<input type="url" value={form.chat_url} onChange={e=>setForm({...form,chat_url:e.target.value})} placeholder="Paste the conversation link when available"/></label><label>What was accomplished?<textarea rows={3} value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/></label><label>Decisions made<textarea rows={3} value={form.decisions} onChange={e=>setForm({...form,decisions:e.target.value})}/></label><label>Evidence or files produced<textarea rows={3} value={form.evidence} onChange={e=>setForm({...form,evidence:e.target.value})}/></label><label>Open questions<textarea rows={3} value={form.open_questions} onChange={e=>setForm({...form,open_questions:e.target.value})}/></label><label>Next actions<textarea rows={3} value={form.next_actions} onChange={e=>setForm({...form,next_actions:e.target.value})}/></label><button>Save to project memory</button></form>}
 <div className="timeline">{sessions.length?sessions.map(s=><article className="timeline-item" key={s.id}><div className="timeline-date">{s.session_date}</div><div><h3>{s.title}</h3>{s.summary&&<p>{s.summary}</p>}{s.decisions&&<p><b>Decision:</b> {s.decisions}</p>}{s.next_actions&&<p><b>Next:</b> {s.next_actions}</p>}{s.chat_url&&<a href={s.chat_url} target="_blank">Open source conversation ↗</a>}</div></article>):<p className="muted">No saved sessions yet. Save the next important ChatGPT discussion here.</p>}</div></section>
}
